# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f76ef47a94b3ca770fdb73a6225efe47f2a043bf2b8fdacabd828ac51d1a942305e178bf830474a8bb6d2b8c21e7f2cb84c8d1c86ff3184d32998f3e47888f9

test:
  secret_key_base: 1e1adc9d073eb094c3a4bcba91b3c3504eace67ce7513caf2ad882e89d43f3d9e0f4ed6939cdff63ac95ac85a0fd1262c353793525ce1634bc458a3d0b3cd090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
